version: '3.8'

services:
  weaviate-test:
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.1
    container_name: meetnearme-weaviate-test
    restart: unless-stopped
    volumes:
      - weaviate_test_data:/var/lib/weaviate
    env_file:
      - ./.env.test
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/v1/.well-known/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  t2v-transformers-test:
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1 # A good default model
    container_name: meetnearme-t2v-transformers-test
    environment:
      ENABLE_CUDA: '0' # Run on CPU for CI/local dev

  # 3. Go Application Test Runner Service
  go-app-tester:
    build:
      context: .
      dockerfile: Dockerfile.go.test # Use the same Dockerfile as your dev app
    container_name: meetnearme-go-app-tester
    volumes:
      - .:/app
    working_dir: /app
    # command: ["go", "test", "-v", "-race", "-cover", "./functions/..."]
    command: sh -c "set -o pipefail && go test -v -race -cover ./functions/... 2>&1 | tee test-results.log"
    env_file:
      - ./.env.test
    depends_on:
      weaviate-test:
        # It's better to wait for health/readiness if you can define a healthcheck
        condition: service_healthy
      t2v-transformers-test:
        condition: service_started

volumes:
  weaviate_test_data:
