services:
  act_combined:
    build:
      context: .
      dockerfile: act-platform/Dockerfile
    image: act-combined
    ports:
      - "${SESHUJOBS_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${SESHUJOBS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SESHUJOBS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SESHUJOBS_POSTGRES_DB}
    restart: unless-stopped
