AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  containerized-aws-sam

  Hello World Go Api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: go

Resources:
  EventFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: main 
      Events:
        GetEvents:
          Type: Api
          Properties: 
            Path: /event
            Method: GET
        PutEvent:
          Type: Api
          Properties:
            Path: /event
            Method: POST
      Policies:
        - AWSLambdaExecute
        - DynamoDBCrudPolicy:
            TableName: !Ref Events
