name: 'go_build_test'
description: 'Build and test Go project'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'

    - name: Install dependencies
      shell: bash
      run: |
        go install github.com/a-h/templ/cmd/templ@latest
        templ generate
        go get ./...

        # go get example.com/octo-examplemodule
        # go get example.com/octo-examplemodule@v1.3.4

    - name: Build Go binaries
      shell: bash
      run: go build -v ./...

    - name: Run Go tests
      shell: bash
      run: go test ./...
