name: go_build_test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: |
          go install github.com/a-h/templ/cmd/templ@latest
          templ generate
          go get ./...

          # go get example.com/octo-examplemodule
          # go get example.com/octo-examplemodule@v1.3.4

      - name: Build Go binaries
        run: go build -v ./...

      - name: Run Go tests
        run: go test ./...
