name: set_aws_creds_env_vars
inputs:
  MEETNEARME_TEST_SECRET:
    description: 'The dummy secret for the MeetNearMe project'
    required: true
  ZENROWS_API_KEY:
    description: 'The API key for the ZenRows environment'
    required: true
runs:
  using: composite
  steps:
    - name: Make envfile
      shell: bash
      run: |
        touch .env
        echo MEET_NEARME_TEST_SECRET=${{ inputs.MEETNEARME_TEST_SECRET }} >> .env
        echo ZENROWS_API_KEY =${{ inputs.ZENROWS_API_KEY }} >> .env
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::626762246796:role/GitHub
        role-duration-seconds: 1200 #adjust as needed for your build time
        aws-region: us-east-1
