name: set_aws_creds_env_vars
runs:
  using: composite
  steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_MEETNEARME_TEST_SECRET: ${{ secrets.MEETNEARME_TEST_SECRET }}
        file_name: .env
        fail_on_empty: true
        sort_keys: true
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::626762246796:role/GitHub
        role-duration-seconds: 1200 #adjust as needed for your build time
        aws-region: us-east-1
