name: set_aws_creds_env_vars
inputs:
  GIT_BRANCH_NAME:
    description: 'The name of the branch being deployed'
    required: false
  MEETNEARME_TEST_SECRET:
    description: 'The dummy secret for the MeetNearMe project'
    required: true
  ZENROWS_API_KEY:
    description: 'The API key for the ZenRows environment'
    required: true
  ROUTE53_HOSTED_ZONE_ID:
    description:
      'The AWS Route53 hosted zone ID for the environment being deployed to'
    required: true
  ROUTE53_HOSTED_ZONE_NAME:
    description:
      'The AWS Route53 hosted zone name for the environment being deployed to'
    required: true
runs:
  using: composite
  steps:
    - name: Make envfile
      shell: bash
      run: |
        touch .env
        echo GIT_BRANCH_NAME=${{ inputs.GIT_BRANCH_NAME }} >> .env
        echo MEETNEARME_TEST_SECRET=${{ inputs.MEETNEARME_TEST_SECRET }} >> .env
        echo ZENROWS_API_KEY=${{ inputs.ZENROWS_API_KEY }} >> .env
        echo ROUTE53_HOSTED_ZONE_ID=${{ inputs.ROUTE53_HOSTED_ZONE_ID }} >> .env
        echo ROUTE53_HOSTED_ZONE_NAME=${{ inputs.ROUTE53_HOSTED_ZONE_NAME }} >> .env
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::626762246796:role/GitHub
        role-duration-seconds: 1200 #adjust as needed for your build time
        aws-region: us-east-1
