export default {
  MEETNEARME_TEST_SECRET: process.env.MEETNEARME_TEST_SECRET,
  SCRAPINGBEE_API_KEY: process.env.SCRAPINGBEE_API_KEY,
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  ZITADEL_CLIENT_ID: process.env.ZITADEL_CLIENT_ID,
  ZITADEL_ENCRYPTION_KEY: process.env.ZITADEL_ENCRYPTION_KEY,
  ZITADEL_INSTANCE_URL: process.env.ZITADEL_INSTANCE_URL,
};
