export default {
  MEETNEARME_TEST_SECRET: process.env.MEETNEARME_TEST_SECRET,
  SCRAPINGBEE_API_KEY: process.env.SCRAPINGBEE_API_KEY,
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  ZITADEL_CLIENT_ID: process.env.ZITADEL_CLIENT_ID,
  ZITADEL_ENCRYPTION_KEY: process.env.ZITADEL_ENCRYPTION_KEY,
  ZITADEL_INSTANCE_HOST: process.env.ZITADEL_INSTANCE_HOST,
  CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID,
  CLOUDFLARE_KV_NAMESPACE_ID: process.env.CLOUDFLARE_KV_NAMESPACE_ID,
  CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN,
  CLOUDFLARE_API_BASE_URL: process.env.CLOUDFLARE_API_BASE_URL,
};
