export default {
  SCRAPINGBEE_API_KEY: process.env.SCRAPINGBEE_API_KEY,
  SCRAPINGBEE_API_URL_BASE: process.env.SCRAPINGBEE_API_URL_BASE,
  GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,
  OPENAI_API_BASE_URL: process.env.OPENAI_API_BASE_URL,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  ZITADEL_CLIENT_ID: process.env.ZITADEL_CLIENT_ID,
  ZITADEL_CLIENT_SECRET: process.env.ZITADEL_CLIENT_SECRET,
  ZITADEL_PROJECT_ID: process.env.ZITADEL_PROJECT_ID,
  ZITADEL_ENCRYPTION_KEY: process.env.ZITADEL_ENCRYPTION_KEY,
  ZITADEL_INSTANCE_HOST: process.env.ZITADEL_INSTANCE_HOST,
  ZITADEL_BOT_ADMIN_TOKEN: process.env.ZITADEL_BOT_ADMIN_TOKEN,
  CLOUDFLARE_API_BASE_URL: process.env.CLOUDFLARE_API_BASE_URL,
  CLOUDFLARE_API_CLIENT_BASE_URL: process.env.CLOUDFLARE_API_CLIENT_BASE_URL,
  CLOUDFLARE_ACCOUNT_ID: process.env.CLOUDFLARE_ACCOUNT_ID,
  CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN,
  CLOUDFLARE_MNM_SUBDOMAIN_KV_NAMESPACE:
    process.env.CLOUDFLARE_MNM_SUBDOMAIN_KV_NAMESPACE,
  CLOUDFLARE_MNM_SUBDOMAIN_KV_NAMESPACE_ID:
    process.env.CLOUDFLARE_MNM_SUBDOMAIN_KV_NAMESPACE_ID,
  _PROD_STRIPE_SECRET_KEY: process.env._PROD_STRIPE_SECRET_KEY,
  _PROD_STRIPE_PUBLISHABLE_KEY: process.env._PROD_STRIPE_PUBLISHABLE_KEY,
  _DEV_STRIPE_SECRET_KEY: process.env._DEV_STRIPE_SECRET_KEY,
  _DEV_STRIPE_PUBLISHABLE_KEY: process.env._DEV_STRIPE_PUBLISHABLE_KEY,
  _DEV_STRIPE_CHECKOUT_WEBHOOK_SECRET:
    process.env._DEV_STRIPE_CHECKOUT_WEBHOOK_SECRET,
  _PROD_STRIPE_CHECKOUT_WEBHOOK_SECRET:
    process.env._PROD_STRIPE_CHECKOUT_WEBHOOK_SECRET,
  _DEV_STRIPE_SUBSCRIPTION_PLAN_GROWTH:
    process.env._DEV_STRIPE_SUBSCRIPTION_PLAN_GROWTH,
  _PROD_STRIPE_SUBSCRIPTION_PLAN_GROWTH:
    process.env._PROD_STRIPE_SUBSCRIPTION_PLAN_GROWTH,
  _DEV_STRIPE_SUBSCRIPTION_PLAN_SEED:
    process.env._DEV_STRIPE_SUBSCRIPTION_PLAN_SEED,
  _PROD_STRIPE_SUBSCRIPTION_PLAN_SEED:
    process.env._PROD_STRIPE_SUBSCRIPTION_PLAN_SEED,
  _DEV_STRIPE_SUBSCRIPTION_WEBHOOK_SECRET:
    process.env._DEV_STRIPE_SUBSCRIPTION_WEBHOOK_SECRET,
  _PROD_STRIPE_SUBSCRIPTION_WEBHOOK_SECRET:
    process.env._PROD_STRIPE_SUBSCRIPTION_WEBHOOK_SECRET,
  USER_TEAM_EMAIL_SCHEMA: process.env.USER_TEAM_EMAIL_SCHEMA,
  USER_TEAM_PASSWORD: process.env.USER_TEAM_PASSWORD,
};
