// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func AdminPage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h2 class=\"text-3xl\">Add an Event Source</h2><br><br><div class=\"flex w-full h-full items-start\"><div class=\"w-1/2 flex-grow card border-2 border-base-300 bg-base-200 rounded-box place-items-center\"><ul class=\"steps steps-vertical\"><li class=\"step step-primary\">Add a Target URL</li><li class=\"step\">Verify Events</li><li class=\"step\">Add to Site</li></ul></div><div class=\"divider divider-horizontal\"></div><div class=\"flex-grow card border-2 border-base-300 bg-base-200 p-10 rounded-box place-items-center\"><form hx-post=\"https://ye7nwfzxnfjkkil7xlxmxxugxy0aggih.lambda-url.us-east-1.on.aws\" hx-ext=\"json-enc\" hx-target=\"#event-candidates\" hx-disabled-elt=\"input[name=&#39;url&#39;], button[type=&#39;submit&#39;]\"><label for=\"url\">Enter a URL that lists events and we will check the site and propose some events that might be on that page (this will take some time)</label> <input name=\"url\" id=\"url\" type=\"text\" class=\"border border-gray-300 p-2 w-full\" placeholder=\"Event source URL\"><br><br><button type=\"submit\" class=\"btn btn-primary\">Search for Events</button></form><br><br><div class=\"w-full\" id=\"event-candidates\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
