{
 "title": "Default",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Http Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_in_flight",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes / 1024 / 1024",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[5m]) / rate(go_gc_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}