name: Deploy Feature Branch (SST)
on:
  push:
    branches:
      - feature/*

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployFeatureSST:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Extract branch name
        shell: bash
        # sed 's|/|-|g' replaces all slashes with hyphens, aws stack names can't have slashes
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | sed 's|/|-|g' >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Configure AWS & Create env file
        uses: './.github/actions/set_aws_creds_env_vars'
        with:
          MEETNEARME_TEST_SECRET: ${{ secrets.MEETNEARME_TEST_SECRET }}
          SCRAPINGBEE_API_KEY: ${{ secrets.SCRAPINGBEE_API_KEY }}
          GIT_BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ZITADEL_CLIENT_ID: ${{ secrets.ZITADEL_CLIENT_ID }}
          ZITADEL_ENCRYPTION_KEY: ${{ secrets.ZITADEL_ENCRYPTION_KEY }}
          ZITADEL_INSTANCE_URL: ${{ secrets.ZITADEL_INSTANCE_URL }}
          ZITADEL_REDIRECT_URI: ${{ secrets.ZITADEL_REDIRECT_URI }}
      - name: Deploy app
        run: |
          npm i && npx sst deploy --stage ${{ steps.extract_branch.outputs.branch }}
