name: Deploy Prod (SST)
on:
  push:
    branches:
      - main

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployProdSST:
    runs-on: ubuntu-latest
    env:
      #Define your envs needed for static generation:
      MEETNEARME_TEST_SECRET: ${{ secrets.MEETNEARME_TEST_SECRET }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: 'Create env file'
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}
        run: |
          echo "MEETNEARME_TEST_SECRET=$(secrets.MEETNEARME_TEST_SECRET)" > .env
        shell: bash
      - name: 'print path'
        run: |
          echo "$(cat .env)"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::626762246796:role/GitHub
          role-duration-seconds: 1200 #adjust as needed for your build time
          aws-region: us-east-1
      - name: Deploy app
        run: |
          npm i && npx sst deploy --stage prod
