name: Deploy Feature Branch (SST)
on:
  push:
    branches:
      - feature/*

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  DeployFeatureSST:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Extract branch name
        shell: bash
        # echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/ | sed 's/\//-/g'}}" >> $GITHUB_OUTPUT
        run: |
          $BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          $BRANCH_NAME=$( "$BRANCH_NAME" | sed 's/\//-/g')
          echo "$BRANCH_NAME"
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Configure AWS & Create env file
        uses: './.github/actions/set_aws_creds_env_vars'
        with:
          MEETNEARME_TEST_SECRET: ${{ secrets.MEETNEARME_TEST_SECRET }}
          ZENROWS_API_KEY: ${{ secrets.ZENROWS_API_KEY }}
          GIT_BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
      - name: Deploy app
        # npm i && node .github/scripts/non-interactive-deploy.js
        # mkdir -p ~/.sst && touch stage && echo "${{ steps.extract_branch.outputs.branch }}" > ~/.sst/stage
        run: |
          echo ${{ steps.extract_branch.outputs.branch }}
          mkdir -p ~/.sst && touch stage && echo "prod-test-ci-branch" > ~/.sst/stage
          npm i && npx sst deploy --stage prod-test-ci-branch
