name: Deploy Dev (SST)
on:
  push:
    branches:
      - develop

# Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  DeployDevSST:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Generate templ code
        uses: './.github/actions/templ_generate'
        with:
          templ_version: 'latest'
          commit: 'false'
      - name: Breakpoint if `templ` generate failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: brianfeister
      - name: Configure AWS & Create env file
        uses: './.github/actions/set_aws_creds_env_vars'
        with:
          MEETNEARME_TEST_SECRET: ${{ secrets.MEETNEARME_TEST_SECRET }}
          SCRAPINGBEE_API_KEY: ${{ secrets.SCRAPINGBEE_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ZITADEL_CLIENT_ID: ${{ secrets.ZITADEL_CLIENT_ID }}
          ZITADEL_ENCRYPTION_KEY: ${{ secrets.ZITADEL_ENCRYPTION_KEY }}
          ZITADEL_INSTANCE_URL: ${{ secrets.ZITADEL_INSTANCE_URL }}
          APEX_URL: ${{ secrets.APEX_DEV_URL }}
          APEX_DEV_URL: ${{ secrets.APEX_DEV_URL }}
      - name: Deploy app
        run: |
          npm i && npx sst deploy --stage dev
      - name: Breakpoint if `npx sst deploy` failed
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: brianfeister
